### ISSUE TITLE
第7步命令里有个小错误

### ISSUE THREAD

**Issue by xnowbzhao** [chenlongwhu/PC2-PU#1]
model-best.pth.tar -> model_best.pth.tar

**Comment by chenlongwhu** [comment]
感谢您的提醒，已经修改了

**Comment by xnowbzhao** [comment]
> 感谢您的提醒，已经修改了

顺便想问一下，您有运行过https://github.com/ninaqy/Flexible-PU中的代码吗？作者提供的模型似乎无法正常工作

**Comment by chenlongwhu** [comment]
>顺便想问一下，您有运行过[https://github.com/ninaqy/Flexible-PU中的代码吗？作者提供的模型似乎无法正常工作](https://github.com/ninaqy/Flexible-PU%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E5%90%97%EF%BC%9F%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BC%BC%E4%B9%8E%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E5%B7%A5%E4%BD%9C)
抱歉，我没有运行过该仓库中的代码。

**Comment by chenlongwhu** [comment]
>顺便想问一下，您有运行过[https://github.com/ninaqy/Flexible-PU中的代码吗？作者提供的模型似乎无法正常工作](https://github.com/ninaqy/Flexible-PU%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E5%90%97%EF%BC%9F%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BC%BC%E4%B9%8E%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E5%B7%A5%E4%BD%9C)

抱歉，我没有运行过该仓库中的代码。
