### ISSUE TITLE
训练数据的生成方式

### ISSUE THREAD

**Issue by xnowbzhao** [chenlongwhu/PC2-PU#2]
您好，我希望与您的论文在多个尺度上进行对比，需要重新训练网络，请问能否提供生成训练数据的代码？谢谢！

**Comment by chenlongwhu** [comment]
> 您好，我希望与您的论文在多个尺度上进行对比，需要重新训练网络，请问能否提供生成训练数据的代码？谢谢！

您好，您是需要mesh模型分割的代码，还是需要采样的代码。

**Comment by xnowbzhao** [comment]
您好，请问您的mesh模型划分是否使用的是pu-net提供的代码？是的话，希望您能提供采样的代码，谢谢！

**Comment by chenlongwhu** [comment]
> 您好，请问您的mesh模型划分是否使用的是pu-net提供的代码？是的话，希望您能提供采样的代码，谢谢！

是的，mesh模型的划分使用的是PU-Net提供的代码进行了部分修改来获得有重叠的补丁对，采样的代码使用的也是PU-Net提供的代码 您可以通过该链接得到 https://github.com/yulequan/PU-Net/blob/master/prepare_data/Poisson_sample.tar。

**Comment by xnowbzhao** [comment]
非常感谢您的帮助，最后我希望能了解一下如何实现有重叠的补丁对，谢谢！

**Comment by chenlongwhu** [comment]
> 非常感谢您的帮助，最后我希望能了解一下如何实现有重叠的补丁对，谢谢！

重叠的补丁对的获取，是在mesh分割的时候，选取两个顶点作为种子点给定半径后可以得到两个带有重叠的补丁（PU-Net代码中的getPatch函数），通过控制种子点的距离和补丁的半径可以得到不同重叠度的补丁。这两天我会整理一下相应的代码并上传，感谢您的关注。
