### ISSUE TITLE
16倍上采样

### ISSUE THREAD

**Issue by ChenDoubleJ** [chenlongwhu/PC2-PU#3]
您好，很感谢您分享的代码。
我在复现论文的时候遇到了一个问题：
首先想请问您在进行16倍上采样的时候需要怎么设置参数？我设置up_ratio=16，gt_dir = "data/test/gt_32768"，n_upsample = 2，但是运行时出现了错误。可以帮助解答一下吗？
或者说直接使用4倍上采样的训练好的网络，在测试的时候仅仅使用使用n_upsample = 2进行16倍上上采样的测试就好，不需要训练16倍上采样的网络呢？
希望您看到的时候，可以回复解答一下，谢谢！

**Comment by chenlongwhu** [comment]
> 您好，很感谢您分享的代码。
我在复现论文的时候遇到了一个问题：
首先想请问您在进行16倍上采样的时候需要怎么设置参数？我设置up_ratio=16，gt_dir = "data/test/gt_32768"，n_upsample = 2，但是运行时出现了错误。可以帮助解答一下吗？
或者说直接使用4倍上采样的训练好的网络，在测试的时候仅仅使用使用n_upsample = 2进行16倍上上采样的测试就好，不需要训练16倍上采样的网络呢？
希望您看到的时候，可以回复解答一下，谢谢！

将up_ratio仍然设置为4，因为我们是使用4倍的上采样模型上采样了两次，这个是follow了以前PU-GAN的实验设置

**Comment by ChenDoubleJ** [comment]
> 

很感谢您的回复！也就是说，直接在测试的时候将n_upsample = 1修改为n_upsample = 2就好，是吗？

**Comment by chenlongwhu** [comment]
> 很感谢您的回复！也就是说，直接在测试的时候将n_upsample = 1修改为n_upsample = 2就好，是吗？

是的，您可以简单的将n_upsample=2，就能完成 16倍的上采样测试

**Comment by ChenDoubleJ** [comment]
> > 很感谢您的回复！也就是说，直接在测试的时候将n_upsample = 1修改为n_upsample = 2就好，是吗？
> 
> 是的，您可以简单的将n_upsample=2，就能完成 16倍的上采样测试

在测试的时候会出现"cd loss"，“hd loss"，是否可以直接将这两个值作为评价指标呢，计算这两个loss的方式和计算cd，hd的评价指标的方式是不是一样的呢？

**Comment by chenlongwhu** [comment]
是的，是将CD和HD直接作为评价指标，计算损失和指标的方式是一样的.

**Comment by ChenDoubleJ** [comment]
> 是的，是将CD和HD直接作为评价指标，计算损失和指标的方式是一样的.

好的，再次感谢您的回复！
