### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by ChenDoubleJ** [chenlongwhu/PC2-PU#4]
您好，我在进行evaluation时出现了问题，请问下面的Icosahedron.off Icosahedron.xyz分别代表什么网格和数据是什么呢？
cd evaluation_code
cmake .
make
./evaluation Icosahedron.off Icosahedron.xyz

**Comment by chenlongwhu** [comment]
我在readme里对评估的命令有相关的说明
> The second argument is the mesh, and the third one is the predicted points. 

输入对应的模型路径和预测的点云文件，即可完成评估

**Comment by ChenDoubleJ** [comment]
> 我在readme里对评估的命令有相关的说明
> 
> > The second argument is the mesh, and the third one is the predicted points.
> 
> 输入对应的模型路径和预测的点云文件，即可完成评估

不好意思，我没有注意到，最后您在论文中说，分patch的方式和pu-net一样，每个物体分了100patch，但是您做的是有两个相邻patch共同输入的，请问每个物体分100patch，其中每个patch都是有和另某些个patch重叠的部分吗？要是的话，pu-net是不是里面的patch也是有重叠的部分。

**Comment by chenlongwhu** [comment]
>不好意思，我没有注意到，最后您在论文中说，分patch的方式和pu-net一样，每个物体分了100patch，但是您做的是有两个相邻patch共同输入的，请问每个物体分100patch，其中每个patch都是有和另某些个patch重叠的部分吗？要是的话，pu-net是不是里面的patch也是有重叠的部分。

这是个好问题，PU-Net和PU-GAN等一些先前的方法，在制作训练集时，采用的是统一的方法，这100个patch之间是存在重叠的部分，但这些模型的输入是一个个单独的patch，并没有考虑到patch之间的关系；我们与之前的方法的区别在于，我们模型的输入是成对的补丁，从成对的补丁中捕获丢失的信息。

**Comment by ChenDoubleJ** [comment]
> > 不好意思，我没有注意到，最后您在论文中说，分patch的方式和pu-net一样，每个物体分了100patch，但是您做的是有两个相邻patch共同输入的，请问每个物体分100patch，其中每个patch都是有和另某些个patch重叠的部分吗？要是的话，pu-net是不是里面的patch也是有重叠的部分。
> 
> 这是个好问题，PU-Net和PU-GAN等一些先前的方法，在制作训练集时，采用的是统一的方法，这100个patch之间是存在重叠的部分，但这些模型的输入是一个个单独的patch，并没有考虑到patch之间的关系；我们与之前的方法的区别在于，我们模型的输入是成对的补丁，从成对的补丁中捕获丢失的信息。

我知道了，谢谢！期待你们有更多的工作出来！

**Comment by chenlongwhu** [comment]
> 我知道了，谢谢！期待你们有更多的工作出来！

感谢关注
