### ISSUE TITLE
测试数据采样

### ISSUE THREAD

**Issue by ChenDoubleJ** [chenlongwhu/PC2-PU#5]
您好，我想请问您在采样测试数据的时候与之前的文章有什么不同吗？

**Comment by chenlongwhu** [comment]
>  您好，我想请问您在采样测试数据的时候与之前的文章有什么不同吗？

没有什么不同，都是用PU-Net提供的代码进行的泊松采样

**Comment by ChenDoubleJ** [comment]
> 
也没有针对于您的任务相邻之间片的关系，有特殊的处理吗？

**Comment by chenlongwhu** [comment]
> 也没有针对于您的任务相邻之间片的关系，有特殊的处理吗？

我的真值和测试数据都是通过泊松采样的方式制作的，也放置在了谷歌云盘里。在inference的过程中，我是为每一个面片选择了一个最佳面片，具体的选取策略在论文的附录中或者在代码中可以看到。

**Comment by ChenDoubleJ** [comment]
> > 也没有针对于您的任务相邻之间片的关系，有特殊的处理吗？
> 
> 我的真值和测试数据都是通过泊松采样的方式制作的，也放置在了谷歌云盘里。在inference的过程中，我是为每一个面片选择了一个最佳面片，具体的选取策略在论文的附录中或者在代码中可以看到。

也就是说采样和之前的论文一样，只是您针对方法多了一个选择最佳面片的工作。

**Comment by chenlongwhu** [comment]
> 也就是说采样和之前的论文一样，只是您针对方法多了一个选择最佳面片的工作。

是的，只是在测试的时候选择了最佳面片。

**Comment by ChenDoubleJ** [comment]
> > 也就是说采样和之前的论文一样，只是您针对方法多了一个选择最佳面片的工作。
> 
> 是的，只是在测试的时候选择了最佳面片。

好的，谢谢您的解答！
